const modes = {
	TOPICS: 'TOPICS',
	LETTER_PREVIEW: 'LETTER_PREVIEW',
	PARAGRAPHS_EDIT: 'PARAGRAPHS_EDIT',
	PARAGRAPHS_PREVIEW: 'PARAGRAPHS_PREVIEW',
	PARAGRAPHS_REORDER: 'PARAGRAPHS_REORDER',
	PARAGRAPHS_DELETION: 'PARAGRAPHS_DELETION',
}

export default modes
