const pages = {
	GET_STARTED: 'GET_STARTED',
	TOPICS: 'TOPICS',
	LETTER_PREVIEW: 'LETTER_PREVIEW',
	PARAGRAPHS_EDIT: 'PARAGRAPHS_EDIT',
	PARAGRAPHS_PREVIEW: 'PARAGRAPHS_PREVIEW',
	PARAGRAPHS_REORDER: 'PARAGRAPHS_REORDER',
	PARAGRAPHS_DELETION: 'PARAGRAPHS_DELETION',
	HELP: 'HELP',
}

export default pages
