type actionType = object

const actionType = {
	SET_DEFAULT_FILTERS: 'SET_DEFAULT_FILTERS',
	SET_SCREEN: 'SET_SCREEN',
	INCREMENT_SCREEN: 'INCREMENT_SCREEN',
	DECREMENT_SCREEN: 'DECREMENT_SCREEN',
	SET_MODE: 'SET_MODE',
	SET_MODE_MODIFIER: 'SET_MODE_MODIFIER',
	SET_ACTIVE_FILTERS: 'SET_ACTIVE_FILTERS',
	SET_ACTIVE_PARAGRAPHS: 'SET_ACTIVE_PARAGRAPHS',
	SET_FILTERED_PARAGRAPHS: 'SET_FILTERED_PARAGRAPHS',
	REORDER_PARAGRAPHS: 'REORDER_PARAGRAPHS',
	DELETE_PARAGRAPH: 'DELETE_PARAGRAPH',
}

export default actionType
