type actionType = object

const actionType = {
	SET_DEFAULT_FILTERS: 'SET_DEFAULT_FILTERS',
	SET_SCREEN: 'SET_SCREEN',
	INCREMENT_SCREEN: 'INCREMENT_SCREEN',
	DECREMENT_SCREEN: 'DECREMENT_SCREEN',
	SET_MODE: 'SET_MODE',
	SET_ACTIVE_TOPICS: 'SET_ACTIVE_TOPICS',
	SET_ACTIVE_PARAGRAPHS: 'SET_ACTIVE_PARAGRAPHS',
	SET_SUGGESTED_PARAGRAPHS: 'SET_SUGGESTED_PARAGRAPHS',
	SET_SELECTED_PARAGRAPHS: 'SET_SELECTED_PARAGRAPHS',
	REORDER_PARAGRAPHS: 'REORDER_PARAGRAPHS',
	DELETE_PARAGRAPH: 'DELETE_PARAGRAPH',
	SET_TOPIC_VIEW: 'SET_TOPIC_VIEW',
}

export default actionType
